// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HowItWorksController from "./how_it_works_controller"
application.register("how-it-works", HowItWorksController)

import MoviesController from "./movies_controller"
application.register("movies", MoviesController)

import RoundVotingController from "./round_voting_controller"
application.register("round-voting", RoundVotingController)

import SubmissionController from "./submission_controller"
application.register("submission", SubmissionController)
